# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/detection_test',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/detection_test',
                'lib_path': 'detection_test'},
  'syms': {'detection_test.core': {'detection_test.core.foo': ('core.html#foo', 'detection_test/core.py')}}}
